'use strict';
const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { mkTempHome, rmRf, readIfExists } = require('./_helpers');

let TMP;
let noiseDetector, files;

before(() => {
  TMP = mkTempHome();
  noiseDetector = require('../lib/noise-detector');
  files = require('../lib/files');
});
after(() => rmRf(TMP));

test('classifyEntry flags LLM extraction prompt', () => {
  const body = '## 2026-05-22\n\n- Extract durable memory candidates from this Claude Code transcript tail. Return ONLY JSON array.\n<!-- source=LLM:Stop -->';
  const reasons = noiseDetector.classifyEntry(body);
  assert.ok(reasons.includes('llm-extraction-prompt'), `expected llm-extraction-prompt, got ${reasons.join(',')}`);
});

test('classifyEntry flags slash command definition headers', () => {
  const body = '## 2026-05-22\n\n- # memory-add\n\nAppend a memory entry into Claude Hermes Memory\n<!-- source=UserPromptSubmit -->';
  const reasons = noiseDetector.classifyEntry(body);
  assert.ok(reasons.includes('slash-command-definition'));
});

test('classifyEntry flags system-reminder tags', () => {
  const body = '## 2026-05-22\n\n- <system-reminder>do this</system-reminder>\n<!-- source=Stop:regex -->';
  const reasons = noiseDetector.classifyEntry(body);
  assert.ok(reasons.includes('system-tag-block'));
});

test('classifyEntry flags local-command-caveat tags', () => {
  const body = '## 2026-05-22\n\n- <local-command-caveat>messages generated by the user</local-command-caveat>\n<!-- -->';
  const reasons = noiseDetector.classifyEntry(body);
  assert.ok(reasons.includes('system-tag-block'));
});

test('classifyEntry flags wrapped "Failure: # memory-..." entries', () => {
  const body = '## 2026-05-22\n\n- Failure: # memory-insights\n<!-- source=Stop:regex category=failure -->';
  const reasons = noiseDetector.classifyEntry(body);
  assert.ok(reasons.includes('wrapped-slash-command') || reasons.includes('slash-command-definition'));
});

test('classifyEntry returns empty for clean entry', () => {
  const body = '## 2026-05-22\n\n- 주력 언어·스택: Java/Spring\n<!-- source=LLM:Stop category=convention -->';
  const reasons = noiseDetector.classifyEntry(body);
  assert.deepEqual(reasons, []);
});

test('cleanFile removes noise entries and keeps clean ones', () => {
  const r = files.appendEntry('MEMORY.md', '주력 스택: Java/Spring', { projectSlug: 'demo' });
  files.appendEntry('MEMORY.md', 'Extract durable memory candidates from this Claude Code transcript tail. Return ONLY JSON array.', { projectSlug: 'demo' });
  files.appendEntry('MEMORY.md', '<system-reminder>foo</system-reminder>', { projectSlug: 'demo' });
  files.appendEntry('MEMORY.md', '깨끗한 entry', { projectSlug: 'demo' });

  const result = noiseDetector.cleanFile(r.file, { dryRun: false });
  assert.equal(result.ok, true);
  assert.ok(result.removed >= 2, `expected at least 2 removed, got ${result.removed}`);
  const after = readIfExists(r.file);
  assert.ok(after.includes('Java/Spring'));
  assert.ok(after.includes('깨끗한 entry'));
  assert.ok(!after.includes('Extract durable memory candidates'));
  assert.ok(!after.includes('<system-reminder>'));
});

test('cleanFile dry-run does not write but reports', () => {
  const r = files.appendEntry('FAILURES.md', '깨끗한 실패 entry-1', { projectSlug: 'demo' });
  files.appendEntry('FAILURES.md', 'Failure: # memory-insights', { projectSlug: 'demo' });
  const before = readIfExists(r.file);
  const result = noiseDetector.cleanFile(r.file, { dryRun: true });
  assert.ok(result.removed >= 1);
  const after = readIfExists(r.file);
  assert.equal(before, after, 'dry-run must not write');
});

test('cleanAll writes cleanup log on non-dry-run', () => {
  files.appendEntry('SKILLS.md', '<memory-context>noise</memory-context>', { projectSlug: 'demo' });
  const result = noiseDetector.cleanAll({ slug: 'demo', dryRun: false, silent: true });
  assert.equal(result.ok, true);
  assert.ok(result.totalRemoved >= 1);
  const logPath = path.join(TMP, '.claude', 'hermes-memory', 'state', 'cleanup-log.jsonl');
  const log = readIfExists(logPath);
  assert.ok(log.length > 0, 'cleanup log should exist');
  assert.ok(log.includes('"system-tag-block"'));
});

test('cleanAll dry-run reports without writing log', () => {
  const logPath = path.join(TMP, '.claude', 'hermes-memory', 'state', 'cleanup-log.jsonl');
  const before = readIfExists(logPath);
  files.appendEntry('CONVENTIONS.md', '<system-reminder>another noise</system-reminder>', { projectSlug: 'demo' });
  noiseDetector.cleanAll({ slug: 'demo', dryRun: true, silent: true });
  const after = readIfExists(logPath);
  assert.equal(before, after, 'dry-run must not append to cleanup log');
});
